#!/usr/bin/env bash
# Run every AUTODOCU Playwright spec, diff the screenshots, and write a report.
#
# Discovers ALL specs under AUTODOCU/Tests/<section>/**/*.spec.ts (the Playwright
# config's testDir is the Tests folder), not just one section.
#
# Screenshots are NOT written straight into Documentation/. They go to a TEMP folder
# first (via AUTODOCU_SHOT_ROOT, honoured by Scripts/playwright/_helpers.ts). Then each fresh
# capture is compared, pixel by pixel, against the committed image:
#   * changed pixels  > 1%  -> a real change, screenshot marked FAIL. By DEFAULT the
#                              committed image is KEPT and the before/after pair is saved
#                              under AUTODOCU/Tests/test_report/ so the report can show a
#                              visual comparison. Pass --accept-changes to instead REPLACE
#                              the committed images with the fresh captures (future baseline).
#   * changed pixels <= 1%  -> the committed image is kept, screenshot marked PASS
# The section rows carry the plain Playwright pass/fail. All of this lands in
# AUTODOCU/Tests/test_report.md (compare_report.mjs writes it).
#
# GENERIC: this file is the same for every app — it is shipped in the autodocu skill
# template and copied on `init`. The generic helpers it drives live in Scripts/ next
# to this file: the app-specific launch/teardown + URL in Scripts/app_control.sh
# (generated by `build` from the Outline `# Run`), and the screenshot diff + report
# in Scripts/compare_report.mjs (plain Node, no extra deps). Tunable settings (e.g.
# the diff threshold) come from the .env next to this file.
#
# Usage:
#   ./run_test.sh                     # run all sections (changed screenshots -> review)
#   ./run_test.sh 1.Some_sec          # optional: pass a Playwright filter through to npm test
#   ./run_test.sh --accept-changes    # adopt changed screenshots as the new baseline
#
# The flag and a filter can be combined, e.g. ./run_test.sh --accept-changes 1.Some_sec
# Works from any directory. Exit code is 0 only if every report row PASSes.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS="$HERE/Scripts"                 # generic helpers live here (moved out of Tests/)
WORKSPACE="$SCRIPTS/playwright"
DOC_ROOT="$HERE/../Documentation"
REPORT="$HERE/test_report.md"

# --- load tunable settings from .env (next to this script) -------------------
# Holds every knob the harness reads (currently AUTODOCU_DIFF_THRESHOLD). The
# template ships a default .env and `init` copies it here.
if [ -f "$HERE/.env" ]; then
  set -a
  # shellcheck source=/dev/null
  . "$HERE/.env"
  set +a
fi
THRESHOLD="${AUTODOCU_DIFF_THRESHOLD:-1}"   # % changed pixels above which a screenshot counts as changed

# --- parse args: pull out --accept-changes; the rest is a passthrough Playwright filter
ACCEPT=0
PW_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --accept-changes) ACCEPT=1 ;;
    *) PW_ARGS+=("$arg") ;;
  esac
done

if [ ! -f "$SCRIPTS/app_control.sh" ]; then
  echo "ERROR: $SCRIPTS/app_control.sh not found (run 'autodocu build' to generate it)." >&2
  exit 1
fi
# app-dependent: APP_URL, start_app(), stop_app()
# shellcheck source=/dev/null
source "$SCRIPTS/app_control.sh"

# --- discover the specs so the summary can report coverage -------------------
SPECS=()
while IFS= read -r line; do SPECS+=("$line"); done < <(find "$HERE" -name '*.spec.ts' -not -path '*/playwright/*' | sort)
if [ "${#SPECS[@]}" -eq 0 ]; then
  echo "ERROR: no *.spec.ts found under $HERE (nothing to run)." >&2
  exit 1
fi
echo "==> Discovered ${#SPECS[@]} spec file(s):"
for s in "${SPECS[@]}"; do echo "      ${s#"$HERE"/}"; done
echo

# --- scratch (temp screenshots + json report + console log) ------------------
TMP_SHOTS="$(mktemp -d)"
JSON_REPORT="$(mktemp)"
LOG="$(mktemp)"

# --- start the app, guaranteeing teardown + scratch cleanup ------------------
APP_STARTED=0
cleanup() {
  [ "$APP_STARTED" = "1" ] && { echo "==> Stopping app"; stop_app; }
  rm -rf "$TMP_SHOTS" "$JSON_REPORT" "$LOG"
}
# cleanup runs once, on EXIT. INT/TERM just request an exit (with the
# conventional 128+signal code); that fires the EXIT trap, which does the
# teardown. Without this, a Ctrl+C during the wait loop would run cleanup but
# then return to the interrupted sleep — leaving the script un-interruptible.
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

echo "==> Starting app"
if ! start_app; then
  echo "ERROR: start_app failed — is the Docker daemon running? (see the error above)." >&2
  exit 1
fi
APP_STARTED=1

echo "==> Waiting for $APP_URL"
up=0
for i in $(seq 1 60); do
  if curl -sf -o /dev/null "$APP_URL"; then echo "      up after ${i}s"; up=1; break; fi
  sleep 1
done
if [ "$up" != "1" ]; then
  echo "ERROR: app did not respond at $APP_URL within 60s." >&2
  exit 1
fi
echo

# --- run all tests (screenshots -> TEMP, results -> JSON) --------------------
echo "==> Running tests (screenshots go to a temp folder first)"
export AUTODOCU_SHOT_ROOT="$TMP_SHOTS"
export PLAYWRIGHT_JSON_OUTPUT_NAME="$JSON_REPORT"
cd "$WORKSPACE"
# testDir is '../..', so with no filter this runs every section's spec.
# list reporter -> console (via tee); json reporter -> $JSON_REPORT (for the report).
npm test -- --reporter=list,json ${PW_ARGS[@]+"${PW_ARGS[@]}"} 2>&1 | tee "$LOG"
status=${PIPESTATUS[0]}
echo

# --- diff screenshots + write test_report.md ---------------------------------
MODE_NOTE="review — changed images kept, before/after saved for comparison"
[ "$ACCEPT" = "1" ] && MODE_NOTE="accept — changed images become the new baseline"
echo "==> Comparing screenshots (threshold ${THRESHOLD}%, ${MODE_NOTE}) and writing report"
if [ ! -s "$JSON_REPORT" ]; then
  echo "ERROR: Playwright produced no JSON report; cannot build $REPORT." >&2
  echo "       (test run exit code was $status)" >&2
  exit "${status:-1}"
fi
node "$SCRIPTS/compare_report.mjs" "$TMP_SHOTS" "$DOC_ROOT" "$HERE" "$JSON_REPORT" "$THRESHOLD" "$REPORT" "$ACCEPT"
overall=$?
echo

# --- summary -----------------------------------------------------------------
echo "=================== SUMMARY ==================="
echo "Spec files discovered : ${#SPECS[@]}"
result_line="$(grep -Ei '[0-9]+ (passed|failed|flaky|skipped|did not run)' "$LOG" | tail -1)"
echo "Playwright result     : ${result_line:-<no result line parsed>}"
echo "Report                : $REPORT"
if [ "$overall" -eq 0 ]; then
  echo "Overall               : PASSED ✓ (all rows passed)"
else
  echo "Overall               : FAILED ✗ (see $REPORT)"
fi
echo "==============================================="
exit "$overall"
