#!/usr/bin/env bash
# Run every AUTODOCU Playwright spec and print a summary.
#
# Discovers ALL specs under AUTODOCU/Tests/<section>/**/*.spec.ts (the Playwright
# config's testDir is the Tests folder), not just one section, and regenerates the
# screenshots under Documentation/<section>/screenshots/ as it goes.
#
# GENERIC: this file is the same for every app — it is shipped in the autodocu skill
# template and copied on `init`. The app-specific launch/teardown + URL live in
# app_control.sh next to this file (generated by `build` from the Outline `# Run`).
#
# Usage:
#   ./run_test.sh              # run all sections
#   ./run_test.sh 1.Some_sec   # optional: pass a Playwright filter through to npm test
#
# Works from any directory. Exit code mirrors the test run (0 = all passed).
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$HERE/playwright"

if [ ! -f "$HERE/app_control.sh" ]; then
  echo "ERROR: $HERE/app_control.sh not found (run 'autodocu build' to generate it)." >&2
  exit 1
fi
# app-dependent: APP_URL, start_app(), stop_app()
# shellcheck source=/dev/null
source "$HERE/app_control.sh"

# --- discover the specs so the summary can report coverage -------------------
SPECS=()
while IFS= read -r line; do SPECS+=("$line"); done < <(find "$HERE" -name '*.spec.ts' -not -path '*/playwright/*' | sort)
if [ "${#SPECS[@]}" -eq 0 ]; then
  echo "ERROR: no *.spec.ts found under $HERE (nothing to run)." >&2
  exit 1
fi
echo "==> Discovered ${#SPECS[@]} spec file(s):"
for s in "${SPECS[@]}"; do echo "      ${s#"$HERE"/}"; done
echo

# --- start the app, guaranteeing teardown ------------------------------------
APP_STARTED=0
cleanup() { [ "$APP_STARTED" = "1" ] && { echo "==> Stopping app"; stop_app; }; }
trap cleanup EXIT INT TERM

echo "==> Starting app"
start_app
APP_STARTED=1

echo "==> Waiting for $APP_URL"
up=0
for i in $(seq 1 60); do
  if curl -sf -o /dev/null "$APP_URL"; then echo "      up after ${i}s"; up=1; break; fi
  sleep 1
done
if [ "$up" != "1" ]; then
  echo "ERROR: app did not respond at $APP_URL within 60s." >&2
  exit 1
fi
echo

# --- run all tests (regenerates screenshots) ---------------------------------
echo "==> Running tests (this regenerates the screenshots)"
LOG="$(mktemp)"
cd "$WORKSPACE"
# testDir is '..', so with no filter this runs every section's spec.
npm test -- "$@" 2>&1 | tee "$LOG"
status=${PIPESTATUS[0]}
echo

# --- summary -----------------------------------------------------------------
echo "=================== SUMMARY ==================="
echo "Spec files discovered : ${#SPECS[@]}"
# Playwright's list reporter prints a totals line like "1 passed (3.0s)".
result_line="$(grep -Ei '[0-9]+ (passed|failed|flaky|skipped|did not run)' "$LOG" | tail -1)"
echo "Playwright result     : ${result_line:-<no result line parsed>}"
shots="$(find "$HERE/../Documentation" -name '*.png' 2>/dev/null | wc -l | tr -d ' ')"
echo "Screenshots on disk   : ${shots}"
if [ "$status" -eq 0 ]; then
  echo "Overall               : PASSED ✓"
else
  echo "Overall               : FAILED ✗ (exit $status)"
fi
echo "==============================================="
rm -f "$LOG"
exit "$status"
