BQ5K:
  cohortTableHandler:
    database:
      databaseId: BQ5K
      databaseName: bigquery5k
      databaseDescription: BigQuery database
    connection:
      connectionDetailsSettings:
          dbms: bigquery
          drv: bigrquery::bigquery()
          project: atlas-development-270609
          billing: atlas-development-270609
          bigint: integer64
      tempEmulationSchema: atlas-development-270609.sandbox
    cdm:
        cdmDatabaseSchema: atlas-development-270609.finngen_omop_dev_5k
        vocabularyDatabaseSchema: atlas-development-270609.finngen_omop_dev_5k
        resultsDatabaseSchema: atlas-development-270609.finngen_omop_results_dev_5k
# AtlasDevelopment-full
BQ:
  cohortTableHandler:
    database:
      databaseId: BQ
      databaseName: bigquery
      databaseDescription: BigQuery database with 500k patients
    connection:
      connectionDetailsSettings:
          dbms: bigquery
          drv: bigrquery::bigquery()
          project: atlas-development-270609
          billing: atlas-development-270609
          bigint: integer64
      tempEmulationSchema: atlas-development-270609.sandbox
    cdm:
        cdmDatabaseSchema: atlas-development-270609.finngen_omop_dev
        vocabularyDatabaseSchema: atlas-development-270609.finngen_omop_dev
        resultsDatabaseSchema: atlas-development-270609.finngen_omop_results_dev
LATEST:
  cohortTableHandler:
    database:
      databaseId: DF13
      databaseName: FinnGen DF13
      databaseDescription: FinnGen database 13
    connection:
      connectionDetailsSettings:
        dbms: bigquery
        drv: bigrquery::bigquery()
        project: <sandboxProject>
        billing: <sandboxProject>
        bigint: integer64
      tempEmulationSchema: <sandboxProject>.sandbox #needed for creating tmp table in BigQuery
    cdm:
      cdmDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      vocabularyDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      resultsDatabaseSchema: finngen-production-library.finngen_omop_result_r13_v3
DEV:
  cohortTableHandler:
    database:
      databaseId: DEV
      databaseName: FinnGen DEV
      databaseDescription: FinnGen database DEV
    connection:
      connectionDetailsSettings:
        dbms: bigquery
        drv: bigrquery::bigquery()
        project: <sandboxProject>
        billing: <sandboxProject>
        bigint: integer64
      tempEmulationSchema: <sandboxProject>.sandbox #needed for creating tmp table in BigQuery
    cdm:
      cdmDatabaseSchema: <sandboxProject>.finngen_omop_dev
      vocabularyDatabaseSchema: <sandboxProject>.finngen_omop_dev
      resultsDatabaseSchema: <sandboxProject>.finngen_omop_result_dev
