#!/usr/bin/env bash
# App-dependent controls for the AUTODOCU test harness.
#
# GENERATED by `autodocu build` from the Outline `# Run` section:
#   docker run --rm -p 8563:8563 ehr_browser   →  http://localhost:8563/
# run_test.sh (the generic runner that sources this file) is identical for
# every app; this is the only app-specific piece.
#
# It defines:
#   APP_URL        the URL run_test.sh polls until the app answers (the tests' baseURL)
#   start_app()    launch the app in the background and return immediately
#   stop_app()     stop exactly what start_app launched (idempotent)

# URL to poll / tests' baseURL (from Outline # Run).
APP_URL="http://localhost:8563/"

# Fixed name so stop_app tears down exactly what start_app launched.
APP_CONTAINER="autodocu_app"

# Launch the app detached. The Outline # Run command is a `docker run`; we inject
# `-d --name "$APP_CONTAINER"` and keep the user's `--rm` so the container is
# removed on stop.
start_app() {
  docker run --rm -d --name "$APP_CONTAINER" -p 8563:8563 ehr_browser >/dev/null
}

# Stop exactly what start_app launched (idempotent; --rm removes the container).
stop_app() {
  docker stop "$APP_CONTAINER" >/dev/null 2>&1 || true
}
